---
# tasks file for arrs
- name: Set up directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0750"
  with_items:
    - "{{ deluge_config_volume }}"
    - "{{ radarr_config_volume }}"
    - "{{ sonarr_config_volume }}"
    - "{{ lidarr_config_volume }}"
    - "{{ jackett_config_volume }}"
    - "{{ arrs_setup_path }}"
  tags:
    - configuration
  become: true

- name: Write configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ arrs_setup_path }}/{{ item }}"
    mode: '0640'
  loop:
    - "docker-compose.yml"
    - "env.deluge.conf"
    - "env.radarr.conf"
    - "env.sonarr.conf"
    - "env.lidarr.conf"
    - "env.jackett.conf"
  tags:
    - configuration

- name: Ensure all requested components are running.
  community.docker.docker_compose:
    project_src: "{{ arrs_setup_path }}"
    build: false
  become: false
